/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.svgkt

import org.svgkt.Elements.a
import org.svgkt.Elements.g
import org.svgkt.Elements.svg
import kotlin.test.Test
import kotlin.test.assertEquals

class LibraryTest {
    @Test
    fun simpleSvgFragment() {
        val frag = fragment {
            svg {
                g("transform" to "rotate(10.0)") {
                    a {


                    }
                }
            }
        }
        val t = frag.toString()


        assertEquals(
            "<svg><g transform=\"rotate(10.0)\"><a></a></g></svg>",
            t
        )
    }

    @Test
    fun svgBuilder() {
        val t = buildFragment {
            svg {
                a(modifier = SvgModifier.rotate(10.0f).rotate(20.0f)) {
                }
            }
        }.toElement().toString()
        assertEquals(
            "<svg><g transform=\"rotate(20.0)\"><g transform=\"rotate(10.0)\"><a></a></g></g></svg>",
            t
        )
    }
}
